// packages/renderer/src/App.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/tauri";
  import { onMount } from "svelte";

  import { navigate } from "~/lib/router";
  import { mainStore } from "~/stores";

  import Root from "./tree/Root.svelte";

  onMount(async () => {
    const has_user = await invoke("load_user") as boolean;

    if (has_user) {
      navigate("/websites");
    }
    else {
      navigate("/setup/user")
    }
  });
</script>

<main class="bg-def transition" style="--hue: {$mainStore}">
  <Root />
</main>

<style>
  main {
    position: fixed;
    inset: 0;
  }
</style>

// packages/renderer/src/App.tsx
import { Component, createEffect, createResource } from 'solid-js';
import { invoke } from "@tauri-apps/api/tauri";
import Root from "./tree/Root";
import router from "~/lib/router";
import mainStore from "~/stores/mainStore";

const App: Component = () => {
  createEffect(async () => {
    let hasUser = await invoke("load_user") as boolean;

    if (hasUser) {
      router.navigate("/projects");
    }
    else {
      router.navigate("/setup/user");
    }
  });

  return (
    <main class="bg-def transition fixed inset-0" style={`--hue: ${mainStore.hue()}`}>
      <Root />
    </main>
  );
};

export default App;
