// packages/renderer/src/tree/Root.tsx
import type { Component } from "solid-js";
import AddProject from "./branches/AddProject";
import Project from "./branches/Project";
import Projects from "./branches/Projects";
import Setup from "./branches/Setup";
import Settings from "./branches/Settings";

const Root: Component = () => {
  return (
    <>
      <AddProject path="/add-project" />
      <Project path="/project-view" />
      <Projects path="/projects" />
      <Setup path="/setup" />
      <Settings path="/settings" />
    </>
  );
};

export default Root;

// packages/renderer/src/router/Root.svelte
<script lang="ts">
  import { Route } from "~/router";

  import Projects from "./routes/projects/Projects.svelte";
  import AddProject from "./routes/AddProject.svelte";
  import Server from "./routes/server/Server.svelte";
  import UserSettings from "./routes/UserSettings.svelte";
  import Setup from "./routes/setup/Setup.svelte";
</script>

<Route path="/websites">
  <Projects />
</Route>
<Route path="/add-website">
  <AddProject />
</Route>
<Route path="/server">
  <Server />
</Route>
<Route path="/settings">
  <UserSettings />
</Route>
<Route path="/setup">
  <Setup />
</Route>
