// packages/renderer/src/router/routes/projects/lib/Project.svelte
<script>
  import Open from "svelte-material-icons/ArrowRight.svelte";
  import Menu from "svelte-material-icons/DotsVertical.svelte";
  import Favorite from "svelte-material-icons/Star.svelte";

  import { stringToHue } from "~/lib/visuals";
  import Button from "~/lib/primitives/Button.svelte";
  import Panel from "~/lib/primitives/Panel.svelte";
  import Flex from "~/lib/helpers/Flex.svelte";

  export let label = "";
</script>

<Panel style={{ hue: stringToHue(label) }}>
  <article>
    <div class="header">
      <div class="title">{label}</div>
      <Flex>
        <Button colored style={{ hue: stringToHue(label) }}>
          <Favorite />
        </Button>
      </Flex>
    </div>
    <p>A short description maybe?</p>
    <!-- <table>
      <thead>
        <tr>
          <th>Team</th>
          <th>Git status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="team-members">
            {#each Array(Math.floor(Math.random() * 3 + 1)) as member}
              <div class="team-member" style={`--hue: ${Math.random() * 360}`} />
            {/each}
          </td>
          <td>Up to date</td>
        </tr>
      </tbody>
    </table> -->

    <Flex justify="space-between">
      <Flex>
        <Button solid colored style={{ hue: stringToHue(label) }} on:click>
          Open
          <Open />
        </Button>
      </Flex>
      <Button colored style={{ hue: stringToHue(label) }}>
        <Menu />
      </Button>
    </Flex>
  </article>
</Panel>

<style lang="scss">
  article {
    display: flex;
    flex-direction: column;
    gap: 1rem;

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    // table {
    //   font-weight: 400;
    // }

    // th {
    //   width: 50%;
    //   --color-a: 40%;
    //   text-align: start;
    //   font-weight: 400;
    // }

    // .team-members {
    //   display: flex;
    // }
    // .team-member {
    //   width: 1.4rem;
    //   aspect-ratio: 1/1;
    //   background: hsl(var(--hue), 40%, 50%);
    //   border-radius: 50%;
    // }
  }
</style>

// packages/renderer/src/tree/branches/Projects/components/Project.tsx
import type { Component } from "solid-js";
import Button from "~/lib/primitives/Button";
import { stringToHue } from "~/lib/visuals";
import mainStore from "~/stores/mainStore";

type IMainProps = {
  label: string;
  onClick: () => void;
};

const Main: Component<IMainProps> = (props) => {
  return (
    <div
      style={`--hue: ${mainStore.hue() + 180 + 10 * (stringToHue(props.label) % 3)};`}
      class="panel bg-srf text-on2 flex flex-col gap-m0"
    >
      <div class="flex flex-col gap-s pd-bs-m0">
        <div class="header">
          <div class="title text-on0 font-semibold">{props.label}</div>
        </div>
        <p>A short description maybe?</p>
      </div>

      <div class="flex gap-s- justify-between">
        <div class="flex">
          <Button style="solid" onClick={props.onClick}>
            Open
            <div class="i-mdi-arrow-right text-m0" />
          </Button>
        </div>
        <Button style="half">
          <div class="i-mdi-dots-vertical text-m0" />
        </Button>
      </div>
    </div>
  );
};

export default Main;
