// packages/renderer/src/lib/router/Route.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { animateIn, animateOut } from "~/lib/visuals";
  import { route } from "~/lib/router";

  const dispatch = createEventDispatcher();

  // Transitions

  const voidTransition = { duration: 0, delay: 0 };

  const routeIn = (node) => {
    if ($route.firstDifferent[1] === pathLast) {
      return animateIn(node);
    } else {
      return voidTransition;
    }
  };

  const routeOut = (node) => {
    if ($route.firstDifferent[0] === pathLast) {
      return animateOut(node);
    } else {
      return voidTransition;
    }
  };

  $: pathLast = path.split("/").pop();

  // State

  $: isOpen = (() => {
    let open = false;

    if (strict) {
      open = $route.current === path;
    } else {
      open = $route.current.startsWith(path);
    }

    if (open) dispatch("open");
    else dispatch("close");

    return open;
  })();

  // Attributes

  export let strict: boolean = false;
  export let path: string;
  let cls: string = "flex flex-col items-stretch";
  export { cls as class };
</script>

{#if isOpen}
  <section class={cls} in:routeIn out:routeOut>
    <slot />
  </section>
{/if}

<style>
  section {
    position: absolute;
    inset: 0;
    overflow: hidden;
  }
</style>

// packages/renderer/src/lib/router/Route.tsx
import { createEffect, createSignal, ParentComponent } from "solid-js";
import router from "./index";

type IRouteProps = {
  path: string;
  strict?: boolean;
  class?: string;
  onOpen?: () => void;
  onClose?: () => void;
};

const Route: ParentComponent<IRouteProps> = (props) => {
  const { route } = router;
  const baseClasses = props.class ?? "absolute inset-0 flex flex-col items-stretch";
  const classes = () => (
    baseClasses
    + (routeIn() ? " animate-in" : "")
    + (routeOut() ? " animate-out" : "")
  );

  // Transitions

  const pathLast = () => props.path.split("/").pop();

  const routeIn = () => route().firstDifferent[1] === pathLast();
  const routeOut = () => route().firstDifferent[0] === pathLast();

  // State

  let timeout = setTimeout(()=>{}, 0);

  const isOpen = () => {
    let open = false;

    if (props.strict) {
      open = route().current === props.path;
    } else {
      open = route().current.startsWith(props.path);
    }

    if (open) props.onOpen?.();
    else props.onClose?.();

    return open;
  };

  const [hasDom, setHasDom] = createSignal(false);

  createEffect(() => {
    if (isOpen()) {
      setHasDom(true);
      clearTimeout(timeout);
    } else {
      timeout = setTimeout(() => {
        setHasDom(false);
      }, 500);
    }
  })

  // Render

  return (
    <>
      {hasDom() && (
        <section class={classes()}>
          {props.children}
        </section>
      )}
    </>
  );
};

export default Route;
