// packages/renderer/src/router/routes/setup/routes/UserSetup.svelte
<script lang="ts">
  import Git from "svelte-material-icons/Git.svelte"
  import Save from "svelte-material-icons/Check.svelte"
  import Panel from "~/lib/primitives/Panel.svelte"
  import Button from "~/lib/primitives/Button.svelte"
  import Input from "~/lib/primitives/Input.svelte"
  import Flex from "~/lib/helpers/Flex.svelte"

  import { inline } from "~/lib/css";

  let username;
  let password;

  const styles = {
    root: inline({ flex: 1, margin: "1rem", marginBlock: "2rem"}),
  };
</script>


<div class="container">
  <Panel hue={100}>
    <Flex direction="column" justify="space-between" class={styles.root} gap={1}>

      <div class="header">
        <div class="git">
          <Git size="2rem"/>
        </div>

        <span>Let's start by setting up your Git credentials</span>
      </div>

      <Flex direction="column" class={inline({width: "100%"})}>
        <Input label="Username" bind:value={username} />
        <Input label="Token" bind:value={password} />
      </Flex>
      <Flex direction="row" justify="space-between">
        <Button>Skip</Button>
        <Button solid>Save</Button>
      </Flex>
    </Flex>
  </Panel>
</div>

<style lang="scss">
  .container {
    max-width: 48rem;
    height: auto;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: auto
  }

  .header {
    margin-block-end: 1rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 1rem;

    span {
      max-width: 60%;
    }
  }

  .git {
    padding: 2rem;
    display: flex;
    background: hsl(var(--hue), 20%, 20%);
    border-radius: 50%;
  }
</style>

// packages/renderer/src/tree/branches/Setup/branches/UserSetup.tsx
import { Component, createSignal } from "solid-js";
import { invoke } from "@tauri-apps/api/tauri";

import router, { Route } from "~/lib/router";
import Error from "~/lib/Error";
import Input from "~/lib/primitives/Input";
import Button from "~/lib/primitives/Button";

const Main: Component<{ path: string }> = (props) => {
  const { navigate } = router;

  let [loading, setLoading] = createSignal(false);
  let [error, setError] = createSignal(undefined);
  let [username, setUsername] = createSignal('');
  let [password, setPassword] = createSignal('');

  const resetState = () => {
    setLoading(false);
    setError(undefined);
    setUsername('');
    setPassword('');
  };

  const save = async () => {
    setLoading(true);
    try {
      let partial = {
        git_username: username,
        git_password: password,
      };
      await invoke("update_user", { partial });
      navigate("/websites");
    } catch (err: any) {
      setError(err);
      console.log(error);
    }
  };

  const skip = () => {
    navigate("/projects");
  };

  return (
    <Route path={props.path} onOpen={resetState}>
      <div class="flex flex-col gap-m0" style="max-width: 48rem; margin: auto;">
        <div class="flex flex-col items-center text-center gap-m--">
          <div class="pd-m-- round-full bg-srf">
            <div class="i-mdi-git text-m--" />
          </div>

          <div class="flex flex-col gap-s-">
            <span class="text-fg-2">
              Welcome to Interfacer!
            </span>
            <span class="text-fg-1">
              Let's start by setting up your Git credentials
            </span>
          </div>
        </div>

        {error() ? (
          <Error error={error} />
        ) : (
          <>
            <div class="flex flex-col gap-s--">
              {/* <Input label="Username" bind:value={username} />
                <Input label="Token" bind:value={password} /> */}
              <Input label="Username" signal={[username, setUsername]} />
              <Input label="Token" signal={[password, setPassword]} />
            </div>
            <div class="flex justify-between">
              <Button onClick={skip}>Skip</Button>
              <Button style="solid" onClick={save}>Save</Button>
            </div>
          </>
        )}
      </div>
    </Route>
  );
};

export default Main;
