// packages/renderer/src/tree/branches/Projects/index.tsx
import { invoke } from "@tauri-apps/api/tauri";
import { Component, createResource, createSignal } from "solid-js";
import router, { Route } from "~/lib/router";
import Button from "~/lib/primitives/Button";
import Progress from "~/lib/primitives/Progress";
import Headerbar from "~/lib/Headerbar";
import Error from "~/lib/Error";
import projectStore from "~/stores/projectStore";

// import { projectStore } from "~/stores/";
import Project from "./components/Project";

const getProjects = async () => (await invoke("get_websites") as any[]);

const Main: Component<{ path: string }> = (props) => {
  const { navigate } = router;

  const [err, setErr] = createSignal<any>();
  const [projects, { refetch }] = createResource(getProjects);

  return (
    <Route path={props.path} onOpen={() => { refetch() }}>
      <Headerbar title="Your projects">
        <div class="flex gap-s-">
          {!err() && (
            <>
              <Button
                style="half"
                onClick={async () => {
                  navigate("/add-project/edit");
                }}
              >
                Add project
                <div class="i-mdi-git text-m0" />
              </Button>
              <Button
                style="half"
                onClick={async () => {
                  navigate("/settings");
                }}
              >
                <div class="i-mdi-cog text-m0" />
              </Button>
            </>
          )}
        </div>
      </Headerbar>

      <div style="overflow: auto">
        {!projects.loading ? (
          <div class="pd-m0 pd-bs-0">
            {!projects.error ? (
              // TODO: Use grid class when unocss-preset supports that
              <div class="gap-s" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(24rem, 1fr));">
                {projects()?.map((project) => (
                  <Project
                    label={project}
                    onClick={() => {
                      projectStore.setName(project)
                      navigate("/project-view");
                    }}
                  />
                ))}
              </div>
            ) : (
              <Error error={projects.error} />
            )}
          </div>
        ) : (
          <Progress />
        )}
      </div>
    </Route>
  );
};

export default Main;

// packages/renderer/src/tree/branches/Pprojects/Projects.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/tauri";
  import { onMount } from "svelte";
  import Add from "svelte-material-icons/Git.svelte";
  import AddLocal from "svelte-material-icons/FolderPlus.svelte";
  import Settings from "svelte-material-icons/Cog.svelte";
  import { navigate } from "~/lib/router";
  import { projectStore } from "~/stores";
  import Project from "./lib/Project.svelte";
  import Progress from "~/lib/primitives/Progress.svelte";
  import Button from "~/lib/primitives/Button.svelte";
  import Headerbar from "~/lib/Headerbar.svelte";

  let status;
  let websites;

  const reloadSites = async () => {
    try {
      websites = await invoke("get_websites");
      status = "Loaded";
    } catch (err) {
      status = err;
    }
  };

  onMount(async () => {
    await reloadSites();
  });
</script>

<section>
  <Headerbar title="Your projects">
    <div class="flex gap-s-" slot="actions">
      {#if status}
        <Button
          half
          on:click={async () => {
            navigate("/add-website/edit");
          }}
        >
          Add project
          <AddLocal />
        </Button>
        <Button
          half
          on:click={async () => {
            navigate("/settings");
          }}
        >
          <Settings />
        </Button>
      {/if}
    </div>
  </Headerbar>

  {#if status}
    {#if websites}
      <div class="websites">
        {#each websites as website}
          <Project
            label={website}
            on:click={() => {
              projectStore.set(website);
              navigate("/project");
            }}
          />
        {/each}
      </div>
    {:else}
      <p>{status}</p>
    {/if}
  {:else}
    <Progress />
  {/if}
</section>

<style lang="postcss">
  section {
    overflow: auto;
  }

  .websites {
    @apply gap-m0
      pd-m0
      pd-bs-0;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(24rem, 1fr));
  }
</style>
