// packages/renderer/src/tree/Root.svelte
<script lang="ts">
  import { Route } from "~/lib/router";

  import Projects from "./branches/Pprojects/Projects.svelte";
  import AddProject from "./branches/AddProject/AddProject.svelte";
  import Project from "./branches/Project/Project.svelte";
  import UserSettings from "./branches/Settings.svelte";
  import Setup from "./branches/Setup/Setup.svelte";
</script>

<Route path="/websites">
  <Projects />
</Route>
<AddProject path="/add-website" />
<Project path="/project"/>
<Route path="/settings">
  <UserSettings />
</Route>
<Route path="/setup">
  <Setup />
</Route>

// packages/renderer/src/tree/Root.tsx
import type { Component } from "solid-js";
import AddProject from "./branches/AddProject";
import Project from "./branches/Project";
import Projects from "./branches/Projects";
import Setup from "./branches/Setup";
import Settings from "./branches/Settings";

const Root: Component = () => {
  return (
    <>
      <AddProject path="/add-project" />
      <Project path="/project-view" />
      <Projects path="/projects" />
      <Setup path="/setup" />
      <Settings path="/settings" />
    </>
  );
};

export default Root;
