// packages/renderer/src/lib/Headerbar.svelte
<script lang="ts">
  import Back from "svelte-material-icons/ChevronLeft.svelte";
  import Button from "~/lib/primitives/Button.svelte";

  export let title = null;
  export let back = null;
</script>

<div class="header-bar">
  <div class="title-side">
    {#if back || $$slots.titleActions}
    <div class="title-actions">
      {#if back}
        <Button half on:click={back}>
          <Back />
        </Button>
      {/if}

      <slot name="titleActions" />
    </div>
    {/if}


    {#if title}
      <h2>{title}</h2>
    {/if}
  </div>

  <slot name="actions" />
</div>

<style lang="postcss">
  .header-bar,
  .title-side,
  .title-actions {
    display: flex;
    align-items: center;

  }

  .header-bar {
    @apply pd-m0
      gap-m0
      justify-between;
  }

  .title-side {
    @apply flex1
      gap-m0;
  }

  .title-actions {
    @apply gap-s-;
  }
</style>

// packages/renderer-solid/src/lib/Headerbar.tsx
import { JSXElement, ParentComponent } from "solid-js";
import Button from "~/lib/primitives/Button";

type IMainProps = {
  title?: string;
  titleActions?: JSXElement;
  onBack?: () => void;
};

const Main: ParentComponent<IMainProps> = (props) => {
  return (
    <div class="flex justify-between items-center pd-m0 gap-m0">
      <div class="flex items-center flex1 gap-m0">
        {(props.onBack || props.titleActions) && (
          <div class="flex items-center gap-s-">
            {props.onBack !== undefined && (
              <Button style="half" onClick={props.onBack}>
                <div class="i-mdi-chevron-left text-m0" />
              </Button>
            )}

            {props.titleActions}
          </div>
        )}

        {props.title && (
          <h2>{props.title}</h2>
        )}
      </div>

      {props.children}
    </div>
  );
};

export default Main;
