// packages/renderer/src/lib/primitives/Button.svelte
<script lang="ts">
  export let type = "button";
  export let half = false;
  export let secondary = false;
  export let solid = false;
  export let disabled = false;

  export let hue: number | null = null;
  let cls: string = "round-m0 pd-m0";
  export { cls as class };
</script>

<button
  class={cls}
  class:is-half={half}
  class:is-secondary={secondary}
  class:is-solid={solid}
  {type}
  {disabled}
  style={`
    ${hue != null ? `--hue: ${hue};` : ""}
  `}
  on:click
>
  <div class="flex items-center justify-center flex-1 gap-m0"><slot /></div>
</button>

<style lang="postcss">
  button {
    @apply flex
      items-stretch
      int-text
      transition
      bg-none
      text-int
      border-none;

    font-weight: 600;

    &:disabled {
      cursor: not-allowed;
    }

    &:not(:disabled) {
      cursor: pointer;

      &:hover,
      &:active {
        @apply bg-int3 text-on-int3;
        --highlight: -10%;
      }

      &:active {
        --highlight: -20%;
      }
    }

    &.is-half {
      @apply bg-int3 text-on-int3;
    }

    &.is-secondary {
      @apply bg-int2 text-on-int2;

      &:not(:disabled) {
        &:hover,
        &:active {
          @apply bg-int2 text-on-int2;
        }
      }
    }

    &.is-solid {
      @apply bg-int text-on-int;

      &:not(:disabled) {
        &:hover,
        &:active {
          @apply bg-int text-on-int;
          --highlight: 10%;
        }

        &:active {
          --highlight: 20%;
        }
      }
    }
  }
</style>

// packages/renderer-solid/src/lib/primitives/Button/index.tsx
import { ParentComponent } from "solid-js";
import styles from './style.module.css';

type IMainProps = {
  type?: "submit" | "reset" | "button";
  style?: "ghost" | "half" | "secondary" | "solid";
  // half?: boolean;
  // secondary?: boolean;
  // solid?: boolean;
  disabled?: boolean;
  hue?: number;
  class?: string;
  onClick?: () => void;
};

const Main: ParentComponent<IMainProps> = (props) => {
  return (
    <button
      class={[
        props.class ?? "round-m0 pd-m0",
        styles.button,
        (() => {
          if (props.style === "solid") return styles.isSolid;
          if (props.style === "secondary") return styles.isSecondary;
          if (props.style === "half") return styles.isHalf;
          return styles.isGhost;
        })(),
      ].join(" ")}
      type={props.type}
      disabled={props.disabled}
      style={`${props.hue != null ? `--hue: ${props.hue};` : ""}`}
      onClick={props.onClick}
    >
      <div class="flex items-center justify-center flex-1 gap-m0">
        {props.children}
      </div>
    </button>
  );
};

export default Main;
